apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: nor14fzkv-go 
  janus-idp.io/tekton: nor14fzkv-go
  backstage.io/kubernetes-id: nor14fzkv-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: nor14fzkv-go
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml