apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: nor14fzkv-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: nor14fzkv-go 
  name: nor14fzkv-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: nor14fzkv-go 
